// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/killswitch": {
            "get": {
                "security": [
                    {
                        "AdminToken": []
                    }
                ],
                "description": "Returns whether the battery is paused. Requires the admin token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get the battery kill switch (admin)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.KillswitchResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "AdminToken": []
                    }
                ],
                "description": "Pauses or resumes all sends and prints. Requires the admin token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Set the battery kill switch (admin)",
                "parameters": [
                    {
                        "description": "paused flag",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.killswitchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.KillswitchResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/users/{id}": {
            "get": {
                "security": [
                    {
                        "AdminToken": []
                    }
                ],
                "description": "Returns balance, reserved and available charges for a user. Requires the admin token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get a user's charges balance (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.BalanceResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/users/{id}/credit": {
            "post": {
                "security": [
                    {
                        "AdminToken": []
                    }
                ],
                "description": "Mock top-up: adds charges to a user's balance. Requires the admin token. Idempotent per idempotencyKey.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Credit charges to a user (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "amount + idempotency key",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.creditRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.AdminCreditResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/users/{id}/reconcile": {
            "get": {
                "security": [
                    {
                        "AdminToken": []
                    }
                ],
                "description": "Recomputes balance and reserved from the ledger entries and compares to the account. Requires the admin token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Reconcile a user's ledger (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "user id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ReconcileResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the authenticated user's id and public key",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.MeResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/balance": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the authenticated user's balance, reserved and available charges",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "charges"
                ],
                "summary": "Charges balance",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.BalanceResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/emulate": {
            "post": {
                "description": "TEST ONLY — emulates a message BOC via tonapi and returns success, total fees and destinations. Enabled only when DEV_SIGN=true.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dev"
                ],
                "summary": "[TO BE DELETED] Dev-only message emulation",
                "parameters": [
                    {
                        "description": "message boc",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.emulateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.EmulateResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/firebase/status": {
            "get": {
                "description": "Verifies the Firestore connection with a live round-trip and reports whether Firebase is reachable",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "firebase"
                ],
                "summary": "Firebase connection status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.FirebaseStatusResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/handler.FirebaseStatusResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns OK status if the API is running",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Check service status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.HealthResponse"
                        }
                    }
                }
            }
        },
        "/message": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Runs the battery decision, reserves charges, relays the user's signed message via the relayer and settles or releases the charges",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "battery"
                ],
                "summary": "Send a gasless message",
                "parameters": [
                    {
                        "description": "message boc",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.sendRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.MessageSentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/price": {
            "get": {
                "description": "Returns the live TON price and the resulting nano-per-charge used for charge computation",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "charges"
                ],
                "summary": "Current charge pricing",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/price.Quote"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/print/execute": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Reserves charges, sends the buffer to the new wallet (buffer-first), settles or releases on result",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "print"
                ],
                "summary": "Execute a printed wallet",
                "parameters": [
                    {
                        "description": "quote id",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.printExecuteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.PrintExecuteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/print/quote": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Computes the buffer and charge cost for printing a new wallet and stores the quote",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "print"
                ],
                "summary": "Quote a printed (gift) wallet",
                "parameters": [
                    {
                        "description": "destination address",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.printQuoteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.PrintQuoteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/print/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the status of a print job",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "print"
                ],
                "summary": "Print job status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "print job id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.PrintStatusResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/products": {
            "get": {
                "description": "Returns the available charge packs (mock catalog until real IAP)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "charges"
                ],
                "summary": "Charge packs catalog",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.ProductsResponse"
                        }
                    }
                }
            }
        },
        "/relayer/dev-send": {
            "post": {
                "description": "TEST ONLY — makes the relayer send TON to an address (deploys the relayer on first send, pays gas). Enabled only when DEV_SIGN=true. Response carries header X-Dev-Route: TO-BE-DELETED.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dev"
                ],
                "summary": "[TO BE DELETED] Dev-only relayer send",
                "parameters": [
                    {
                        "type": "string",
                        "description": "destination address",
                        "name": "to",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "amount in TON (default 0.05)",
                        "name": "amount",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "optional comment",
                        "name": "comment",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.RelayerDevSendResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/relayer/status": {
            "get": {
                "description": "Shows the relayer wallet address and its on-chain balance and seqno (reads TON testnet)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "relayer"
                ],
                "summary": "Relayer status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.RelayerStatusResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ton-proof/check": {
            "post": {
                "description": "Verifies a ton_proof signature for a v5R1 wallet, resolves the user by public key, and returns a session JWT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Verify ton_proof and issue a JWT",
                "parameters": [
                    {
                        "description": "ton_proof payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tonproof.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.TonProofCheckResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ton-proof/dev-sign": {
            "get": {
                "description": "TEST ONLY — signs a ton_proof for a fixed test wallet from a payload, so /ton-proof/check can be exercised without a real wallet. Enabled only when DEV_SIGN=true. Response carries header X-Dev-Route: TO-BE-DELETED.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dev"
                ],
                "summary": "[TO BE DELETED] Dev-only ton_proof signer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "payload from /ton-proof/payload",
                        "name": "payload",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "app domain (default localhost)",
                        "name": "domain",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/tonproof.Request"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ton-proof/payload": {
            "get": {
                "description": "Returns a single-use payload (nonce) that the wallet must sign for ton_proof login",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Generate ton_proof payload",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.PayloadResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/transactions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the authenticated user's ledger entries, newest first",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "charges"
                ],
                "summary": "Charges history",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.TransactionsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/wallet/emulate": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Runs static checks, emulation and policy over a message BOC and returns Supported-By-Battery / Allowed-By-Battery / Reject-Reason plus the charge cost",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "battery"
                ],
                "summary": "Emulate a message and return the battery decision",
                "parameters": [
                    {
                        "description": "message boc",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.walletEmulateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handler.DecisionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.AdminCreditResponse": {
            "type": "object",
            "properties": {
                "available": {
                    "type": "integer"
                },
                "balance": {
                    "type": "integer"
                },
                "entryId": {
                    "type": "string"
                },
                "idempotent": {
                    "type": "boolean"
                },
                "reserved": {
                    "type": "integer"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "handler.BalanceResponse": {
            "type": "object",
            "properties": {
                "available": {
                    "type": "integer"
                },
                "balance": {
                    "type": "integer"
                },
                "reserved": {
                    "type": "integer"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "handler.DecisionResponse": {
            "type": "object",
            "properties": {
                "allowed": {
                    "type": "boolean"
                },
                "charge": {
                    "type": "integer"
                },
                "rejectReason": {
                    "type": "string"
                },
                "supported": {
                    "type": "boolean"
                }
            }
        },
        "handler.EmulateResponse": {
            "type": "object",
            "properties": {
                "destinations": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "outMessages": {
                    "type": "integer"
                },
                "success": {
                    "type": "boolean"
                },
                "totalFeesNano": {
                    "type": "integer"
                }
            }
        },
        "handler.EntryDTO": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "balanceAfter": {
                    "type": "integer"
                },
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "op": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "reservedAfter": {
                    "type": "integer"
                }
            }
        },
        "handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "handler.FirebaseStatusResponse": {
            "type": "object",
            "properties": {
                "connected": {
                    "type": "boolean"
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "handler.HealthResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "handler.KillswitchResponse": {
            "type": "object",
            "properties": {
                "paused": {
                    "type": "boolean"
                }
            }
        },
        "handler.MeResponse": {
            "type": "object",
            "properties": {
                "publicKey": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "handler.MessageSentResponse": {
            "type": "object",
            "properties": {
                "charge": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "txHash": {
                    "type": "string"
                }
            }
        },
        "handler.PayloadResponse": {
            "type": "object",
            "properties": {
                "payload": {
                    "type": "string"
                }
            }
        },
        "handler.PrintExecuteResponse": {
            "type": "object",
            "properties": {
                "charge": {
                    "type": "integer"
                },
                "quoteId": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "txHash": {
                    "type": "string"
                }
            }
        },
        "handler.PrintQuoteResponse": {
            "type": "object",
            "properties": {
                "bufferTON": {
                    "type": "string"
                },
                "charge": {
                    "type": "integer"
                },
                "expiresAt": {
                    "type": "integer"
                },
                "quoteId": {
                    "type": "string"
                }
            }
        },
        "handler.PrintStatusResponse": {
            "type": "object",
            "properties": {
                "bufferTON": {
                    "type": "string"
                },
                "charge": {
                    "type": "integer"
                },
                "quoteId": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "toAddress": {
                    "type": "string"
                },
                "txHash": {
                    "type": "string"
                }
            }
        },
        "handler.ProductDTO": {
            "type": "object",
            "properties": {
                "charges": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "price": {
                    "type": "string"
                }
            }
        },
        "handler.ProductsResponse": {
            "type": "object",
            "properties": {
                "products": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.ProductDTO"
                    }
                }
            }
        },
        "handler.ReconcileResponse": {
            "type": "object",
            "properties": {
                "accountBalance": {
                    "type": "integer"
                },
                "accountReserved": {
                    "type": "integer"
                },
                "computedBalance": {
                    "type": "integer"
                },
                "computedReserved": {
                    "type": "integer"
                },
                "consistent": {
                    "type": "boolean"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "handler.RelayerDevSendResponse": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "string"
                },
                "explorer": {
                    "type": "string"
                },
                "from": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                },
                "txHash": {
                    "type": "string"
                }
            }
        },
        "handler.RelayerStatusResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "balanceNano": {
                    "type": "integer"
                },
                "deployed": {
                    "type": "boolean"
                },
                "error": {
                    "type": "string"
                },
                "online": {
                    "type": "boolean"
                },
                "seqno": {
                    "type": "integer"
                }
            }
        },
        "handler.TonProofCheckResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "expiresAt": {
                    "type": "integer"
                },
                "newUser": {
                    "type": "boolean"
                },
                "publicKey": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "handler.TransactionsResponse": {
            "type": "object",
            "properties": {
                "transactions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handler.EntryDTO"
                    }
                },
                "userId": {
                    "type": "string"
                }
            }
        },
        "handler.creditRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "idempotencyKey": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                }
            }
        },
        "handler.emulateRequest": {
            "type": "object",
            "properties": {
                "boc": {
                    "type": "string"
                },
                "ignoreSignature": {
                    "type": "boolean"
                }
            }
        },
        "handler.killswitchRequest": {
            "type": "object",
            "properties": {
                "paused": {
                    "type": "boolean"
                }
            }
        },
        "handler.printExecuteRequest": {
            "type": "object",
            "properties": {
                "quoteId": {
                    "type": "string"
                }
            }
        },
        "handler.printQuoteRequest": {
            "type": "object",
            "properties": {
                "toAddress": {
                    "type": "string"
                }
            }
        },
        "handler.sendRequest": {
            "type": "object",
            "properties": {
                "boc": {
                    "type": "string"
                },
                "ignoreSignature": {
                    "type": "boolean"
                }
            }
        },
        "handler.walletEmulateRequest": {
            "type": "object",
            "properties": {
                "boc": {
                    "type": "string"
                },
                "ignoreSignature": {
                    "type": "boolean"
                }
            }
        },
        "price.Quote": {
            "type": "object",
            "properties": {
                "centsPerCharge": {
                    "type": "integer"
                },
                "currency": {
                    "type": "string"
                },
                "fallback": {
                    "type": "boolean"
                },
                "nanoPerCharge": {
                    "type": "integer"
                },
                "tonPrice": {
                    "type": "number"
                }
            }
        },
        "tonproof.Domain": {
            "type": "object",
            "properties": {
                "length_bytes": {
                    "type": "integer"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "tonproof.Proof": {
            "type": "object",
            "properties": {
                "domain": {
                    "$ref": "#/definitions/tonproof.Domain"
                },
                "payload": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "tonproof.Request": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "network": {
                    "type": "string"
                },
                "proof": {
                    "$ref": "#/definitions/tonproof.Proof"
                },
                "public_key": {
                    "type": "string"
                },
                "wallet_state_init": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "AdminToken": {
            "type": "apiKey",
            "name": "X-Admin-Token",
            "in": "header"
        },
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Battery implementation for TON network",
	Description:      "Backend service for the Cryptocash Battery on the TON network.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
